server:
  internalPort: 5000
  externalPort: 0
  runMode: release
  domain: localhost
cors:
  allowOrigins: "*"
postgres:
  host: postgres_container
  port: 5432
  user: postgres
  password: admin
  dbName: ecommerce
  sslMode: disable
  maxIdleConns: 15
  maxOpenConns: 100
  connMaxLifetime: 5
redis:
  host: redis_container
  port: 6379
  password: password
  db: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  poolSize: 10
  poolTimeout: 15
  idleCheckFrequency: 500
password:
  includeChars: true
  includeDigits: true
  minLength: 6
  maxLength: 64
  includeUppercase: true
  includeLowercase: true
jwt:
  secret: "mySecretKey"
  refreshSecret: "mySecretKey"
  accessTokenExpireDuration: 60
  refreshTokenExpireDuration: 1440
zarinpal:
  merchantId: "your_merchant_id_here"
  # Replace with your actual Zarinpal merchant ID
  paymentRequestUrl: "https://payment.zarinpal.com/pg/v4/payment/request.json"
  paymentVerifyUrl: "https://payment.zarinpal.com/pg/v4/payment/verify.json"
  paymentPageUrl: "https://payment.zarinpal.com/pg/StartPay/"
  # Sandbox mode is used for testing purposes
  sandboxPaymentRequestUrl: "https://sandbox.zarinpal.com/pg/v4/payment/request.json"
  sandboxPaymentVerifyUrl: "https://sandbox.zarinpal.com/pg/v4/payment/verify.json"
  sandboxPaymentPageUrl: "https://sandbox.zarinpal.com/pg/StartPay/"
  # Callback URL for payment verification
  callbackUrl: "localhost:5000/payment/verify"
  sandbox: true